# Generated by Django 3.2.15 on 2022-09-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220919_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Account number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Card number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shaba_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Shaba number'),
        ),
    ]
