# Generated by Django 3.2.15 on 2022-08-21 13:17

import damage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Type of damage')),
            ],
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=damage.models.uuid_hex, editable=False, max_length=500, unique=True)),
                ('billing_id', models.CharField(max_length=100, verbose_name='Billing ID')),
                ('last_bill_image', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Last bill image')),
                ('national_card_image', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='National card image')),
                ('ownership_doc_image', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Ownership document image')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount_of_damages', models.FloatField(verbose_name='Amount of damages')),
                ('status', models.IntegerField(choices=[(1, 'TODO'), (2, 'In progress'), (3, 'Done'), (4, 'Failure'), (5, 'Lack of sufficient information')], default=1, verbose_name='Status')),
                ('done_date', models.DateTimeField(blank=True, null=True, verbose_name='done at')),
                ('operator_description', models.TextField(blank=True, null=True, verbose_name='Operator_Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to='damage.operator', verbose_name='Operator')),
                ('type_of_damage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to='damage.typeofdamage', verbose_name='Type of damage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('damage_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='damage.damagereport', verbose_name='Damage report')),
            ],
        ),
    ]
