# Generated by Django 3.2.15 on 2022-08-21 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('damage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports_operator', to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='type_of_damage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_damage_reports', to='damage.typeofdamage', verbose_name='Type of damage'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_damage_reports', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
