# Generated by Django 3.2.15 on 2022-08-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0003_auto_20220829_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date-Time'),
        ),
    ]
