# Generated by Django 3.2.15 on 2022-09-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0004_alter_damagereport_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='date_time',
            field=models.DateTimeField(default=None, verbose_name='Date-Time'),
            preserve_default=False,
        ),
    ]
