# Generated by Django 3.2.15 on 2022-09-19 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('damage', '0006_auto_20220905_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank branch'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank name'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports_paid_user', to=settings.AUTH_USER_MODEL, verbose_name='Paid by'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid at'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='payment_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Payment code'),
        ),
    ]
