# Generated by Django 3.2.15 on 2022-09-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0007_auto_20220919_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'Not paid'), (2, 'Paid')], default=1, verbose_name='Payment status'),
        ),
    ]
