# Generated by Django 3.2.15 on 2022-09-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0008_damagereport_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagereport',
            name='paid_by',
        ),
    ]
