# Generated by Django 3.2.15 on 2022-08-24 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suggestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='email',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
